### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by JvB94** [0xagil/Fansale-Bot#1]
Hey,
cool project, unfortunately I get this error after starting. What am I doing wrong?

```
root@TestServer:~/Fansale-Bot# python3 bot_v3.py
Traceback (most recent call last):
  File "bot_v3.py", line 9, in <module>
    from src.modules.scraper import Monitor
  File "/root/Fansale-Bot/src/modules/scraper.py", line 54
    match status:
          ^
SyntaxError: invalid syntax
```

**Comment by 0xagil** [comment]
Make sure to run Python 3.10+
